### ISSUE TITLE
TypeError: app.getPath is not a function

### ISSUE THREAD

**Issue by vinnyp** [szwacz/electron-boilerplate#11]
I followed your quick start instructions and I'm hitting an error after I run `npm start` on OSX

I'm running node v0.12.4.

```bash
$ npm start

> @ start /Users/vinny/Projects/Personal/electron-boilerplate
> node ./tasks/start

[21:05:53] Using gulpfile ~/Projects/Personal/electron-boilerplate/gulpfile.js
[21:05:53] Starting 'clean'...
[21:05:53] Finished 'clean' after 3.66 ms
[21:05:53] Starting 'transpile'...
[21:05:53] Starting 'less'...
[21:05:53] Starting 'copy'...
[21:05:53] Starting 'finalize'...
[21:05:53] Finished 'finalize' after 2.72 ms
[21:05:53] Finished 'less' after 87 ms
[21:05:53] Finished 'transpile' after 122 ms
[21:05:53] Finished 'copy' after 239 ms
[21:05:53] Starting 'build'...
[21:05:53] Finished 'build' after 11 μs
/Users/vinny/Projects/Personal/electron-boilerplate/app/vendor/electron_boilerplate/window_state.js:12
    var userDataDir = jetpack.cwd(app.getPath('userData'));
                                      ^
TypeError: app.getPath is not a function
    at module.exports (/Users/vinny/Projects/Personal/electron-boilerplate/app/vendor/electron_boilerplate/window_state.js:12:39)
    at Object.<anonymous> (/Users/vinny/Projects/Personal/electron-boilerplate/app/main.js:12:23)
    at Module._compile (module.js:418:26)
    at Object.Module._extensions..js (module.js:436:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:298:12)
    at Module.require (module.js:353:17)
    at require (module.js:372:17)
    at Object.<anonymous> (/Users/vinny/Projects/Personal/electron-boilerplate/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/browser/api/lib/dialog.js:11:9)
    at Object.<anonymous> (/Users/vinny/Projects/Personal/electron-boilerplate/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/browser/api/lib/dialog.js:153:4)
[21:05:54] Using gulpfile ~/Projects/Personal/electron-boilerplate/gulpfile.js
[21:05:54] Starting 'watch'...
[21:05:54] Finished 'watch' after 114 ms
```

Here's the output from the `npm install`:

```bash
$ npm install
npm WARN package.json @ No repository field.
npm WARN package.json @ No license field.
npm WARN peerDependencies The peer dependency stream-browserify@* included from bl will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
\
> fs-xattr@0.1.6 install /Users/vinny/Projects/Personal/electron-boilerplate/node_modules/appdmg/node_modules/fs-xattr
> node-gyp rebuild

  CXX(target) Release/obj.target/xattr/src/xattr.o
  SOLINK_MODULE(target) Release/xattr.node

> electron-prebuilt@0.26.1 postinstall /Users/vinny/Projects/Personal/electron-boilerplate/node_modules/electron-prebuilt
> node install.js

|
> macos-alias@0.2.6 install /Users/vinny/Projects/Personal/electron-boilerplate/node_modules/appdmg/node_modules/ds-store/node_modules/macos-alias
> node-gyp rebuild

  CXX(target) Release/obj.target/volume/src/volume.o
  SOLINK_MODULE(target) Release/volume.node

> @ postinstall /Users/vinny/Projects/Personal/electron-boilerplate
> node ./tasks/app_npm_install

npm WARN package.json electron-boilerplate@0.1.0 No repository field.
npm WARN package.json electron-boilerplate@0.1.0 No README data
npm WARN package.json electron-boilerplate@0.1.0 No license field.
fs-jetpack@0.6.5 node_modules/fs-jetpack
├── rimraf@2.2.8
├── q@1.0.1
├── mkdirp@0.5.0 (minimist@0.0.8)
└── minimatch@2.0.1 (brace-expansion@1.1.0)
rcedit@0.3.0 node_modules/rcedit

q@1.4.1 node_modules/q

yargs@1.3.3 node_modules/yargs

asar@0.6.1 node_modules/asar
├── chromium-pickle-js@0.1.0
├── commander@2.3.0
├── mkdirp@0.5.1 (minimist@0.0.8)
├── glob@5.0.10 (path-is-absolute@1.0.0, inherits@2.0.1, once@1.3.2, inflight@1.0.4)
├── cuint@0.1.5
└── minimatch@2.0.4 (brace-expansion@1.1.0)

gulp-util@3.0.5 node_modules/gulp-util
├── array-differ@1.0.0
├── array-uniq@1.0.2
├── object-assign@2.1.1
├── beeper@1.1.0
├── lodash._reescape@3.0.0
├── lodash._reevaluate@3.0.0
├── lodash._reinterpolate@3.0.0
├── replace-ext@0.0.1
├── minimist@1.1.1
├── vinyl@0.4.6 (clone-stats@0.0.1, clone@0.2.0)
├── chalk@1.0.0 (escape-string-regexp@1.0.3, ansi-styles@2.0.1, supports-color@1.3.1, strip-ansi@2.0.1, has-ansi@1.0.3)
├── lodash.template@3.6.1 (lodash._basevalues@3.0.0, lodash._basetostring@3.0.0, lodash._basecopy@3.0.1, lodash.templatesettings@3.1.0, lodash.restparam@3.6.1, lodash.escape@3.0.0, lodash._isiterateecall@3.0.9, lodash.keys@3.1.1)
├── through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.33)
├── multipipe@0.1.2 (duplexer2@0.0.2)
└── dateformat@1.0.11 (get-stdin@4.0.1, meow@3.3.0)

fs-jetpack@0.6.5 node_modules/fs-jetpack
├── rimraf@2.2.8
├── q@1.0.1
├── mkdirp@0.5.0 (minimist@0.0.8)
└── minimatch@2.0.1 (brace-expansion@1.1.0)

vinyl-map@1.0.1 node_modules/vinyl-map
├── through2@0.4.2 (xtend@2.1.2, readable-stream@1.0.33)
├── new-from@0.0.3 (readable-stream@1.1.13)
├── stream-browserify@1.0.0 (inherits@2.0.1, readable-stream@1.1.13)
└── bl@0.7.0 (readable-stream@1.0.33)

gulp@3.9.0 node_modules/gulp
├── pretty-hrtime@1.0.0
├── interpret@0.6.2
├── deprecated@0.0.1
├── archy@1.0.0
├── tildify@1.1.0 (os-homedir@1.0.0)
├── minimist@1.1.1
├── v8flags@2.0.7 (user-home@1.1.1)
├── chalk@1.0.0 (escape-string-regexp@1.0.3, ansi-styles@2.0.1, supports-color@1.3.1, strip-ansi@2.0.1, has-ansi@1.0.3)
├── semver@4.3.6
├── orchestrator@0.3.7 (stream-consume@0.1.0, sequencify@0.0.7, end-of-stream@0.1.5)
├── liftoff@2.1.0 (extend@2.0.1, rechoir@0.6.1, flagged-respawn@0.3.1, resolve@1.1.6, findup-sync@0.2.1)
└── vinyl-fs@0.3.13 (graceful-fs@3.0.8, strip-bom@1.0.0, defaults@1.0.2, vinyl@0.4.6, mkdirp@0.5.1, through2@0.6.5, glob-stream@3.1.18, glob-watcher@0.0.6)

esperanto@0.6.34 node_modules/esperanto
├── minimist@1.1.1
├── chalk@1.0.0 (escape-string-regexp@1.0.3, ansi-styles@2.0.1, supports-color@1.3.1, strip-ansi@2.0.1, has-ansi@1.0.3)
├── acorn@1.2.2
├── sander@0.2.4 (graceful-fs@3.0.8, mkdirp@0.5.1, rimraf@2.4.0, es6-promise@2.3.0)
└── magic-string@0.4.9 (vlq@0.2.1)

gulp-less@1.3.9 node_modules/gulp-less
├── convert-source-map@0.4.1
├── lodash.defaults@2.4.1 (lodash._objecttypes@2.4.1, lodash.keys@2.4.1)
├── through2@0.5.1 (xtend@3.0.0, readable-stream@1.0.33)
├── vinyl-sourcemaps-apply@0.1.4 (source-map@0.1.43)
└── less@1.7.5 (graceful-fs@3.0.8, mime@1.2.11, mkdirp@0.5.1, clean-css@2.2.23, source-map@0.1.43, request@2.40.0)

electron-prebuilt@0.26.1 node_modules/electron-prebuilt
├── extract-zip@1.0.3 (debug@0.7.4, minimist@0.1.0, async@0.9.0, yauzl@2.3.1, mkdirp@0.5.0, through2@0.6.3, concat-stream@1.5.0)
└── electron-download@1.0.5 (path-exists@1.0.0, home-path@0.1.2, mkdirp@0.5.1, mv@2.1.0, nugget@1.5.2)

appdmg@0.3.2 node_modules/appdmg
├── minimist@0.0.10
├── image-size@0.2.5
├── async@0.7.0
├── temp@0.7.0 (rimraf@2.2.8)
├── fs-xattr@0.1.6 (nan@1.8.4)
└── ds-store@0.1.4 (unorm@1.3.3, bplist-creator@0.0.5, macos-alias@0.2.6)
```

**Comment by szwacz** [comment]
`app.getPath` is a part of Electron API, so I can't imagine this is some bug in the project.
Googling led me to this article: http://ingorichter.blogspot.com/2015/05/electron-mystery-on-osx-solved.html

**Comment by vinnyp** [comment]
Thanks! I removed NODE_PATH and it worked fine. Now I just need to figure out why my NODE_PATH is busted.
