### ISSUE TITLE
How can I debug my electron app?

### ISSUE THREAD

**Issue by sonnhy** [szwacz/electron-boilerplate#140]
As this project is about starting, and I've no idea where to ask for rollup and electron.
If anyone can point me to some guide or help me figure out why I'm getting error build (npm start), I'll be glad.
I'm still kind of new to programming in js and electron. I've no idea where to look for errors as it seems that gulp encounters problems on rollup, which is a module, but this doesn't tell me where the errors are in my files.

```javascript
Tommaso@Phoenix MINGW64 /d/workspace/Web/vvvvforce_webdriverio (master)
$ npm start

> @ start D:\workspace\Web\vvvvforce_webdriverio
> gulp start

[01:07:06] Using gulpfile D:\workspace\Web\vvvvforce_webdriverio\gulpfile.js
[01:07:06] Starting 'clean'...
[01:07:06] Starting 'watch'...
[01:07:06] Finished 'watch' after 11 ms
[01:07:10] Finished 'clean' after 3.99 s
[01:07:10] Starting 'bundle'...
[01:07:10] Starting 'less'...
[01:07:10] Starting 'copy'...
[01:07:10] Starting 'finalize'...
[01:07:10] Finished 'finalize' after 4.44 ms
[01:07:10] 'bundle' errored after 72 ms
[01:07:10] Error: Could not load null: path must be a string
    at D:\workspace\Web\vvvvforce_webdriverio\node_modules\rollup\dist\rollup.js:7834:10
    at tryCatch (D:\workspace\Web\vvvvforce_webdriverio\node_modules\rollup\dist\rollup.js:337:12)
    at invokeCallback (D:\workspace\Web\vvvvforce_webdriverio\node_modules\rollup\dist\rollup.js:349:13)
    at publish (D:\workspace\Web\vvvvforce_webdriverio\node_modules\rollup\dist\rollup.js:320:7)
    at publishRejection (D:\workspace\Web\vvvvforce_webdriverio\node_modules\rollup\dist\rollup.js:270:3)
    at flush (D:\workspace\Web\vvvvforce_webdriverio\node_modules\rollup\dist\rollup.js:131:5)
    at nextTickCallbackWith0Args (node.js:456:9)
    at process._tickDomainCallback (node.js:426:13)
[01:07:10] Finished 'less' after 84 ms
[01:07:31] Finished 'copy' after 21 s
```

**Comment by sonnhy** [comment]
The errore was in the in the build gulp task, on bundle.
