### ISSUE TITLE
test build fail with switch to electron-mocha

### ISSUE THREAD

**Issue by leshow** [szwacz/electron-boilerplate#152]
I have a project based off this one, I had kept it up to date as of the Feb 29 commit.

Recently I re-based and the app that I built on top of this boilerplate has failed to run it's tests.

the app will start and run fine, but if I run tests via the new way with electron-mocha, I start to encounter several build errors.

firstly:
any import in any of my app/*.js files that relies on the `window` object such as `swfobject`, 

```
[ReferenceError: window is not defined]
ReferenceError: window is not defined
    at /home/evan/electron/electron-boilerplate/build/node_modules/swfobject/index.js:4:190
    at Object.<anonymous> (/home/evan/electron/electron-boilerplate/build/node_modules/swfobject/index.js:4:10154)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at /home/evan/electron/electron-boilerplate/build/spec.js:14:33
    at Object.<anonymous> (/home/evan/electron/electron-boilerplate/build/spec.js:942:2)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at /home/evan/electron/electron-boilerplate/node_modules/mocha/lib/mocha.js:219:27
    at Array.forEach (native)
    at Mocha.loadFiles (/home/evan/electron/electron-boilerplate/node_modules/mocha/lib/mocha.js:216:14)
    at Mocha.run (/home/evan/electron/electron-boilerplate/node_modules/mocha/lib/mocha.js:468:10)
    at Object.run (/home/evan/electron/electron-boilerplate/node_modules/electron-mocha/mocha.js:60:28)
    at EventEmitter.<anonymous> (/home/evan/electron/electron-boilerplate/node_modules/electron-mocha/index.js:45:11)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
npm ERR! Test failed.  See above for more details.
```

secondly, if I just comment out swfobject to see if I can get further in the test build process:

```
[TypeError: Cannot read property 'app' of undefined]
TypeError: Cannot read property 'app' of undefined
    at /home/evan/electron/electron-boilerplate/build/spec.js:208:30
    at Object.<anonymous> (/home/evan/electron/electron-boilerplate/build/spec.js:941:2)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at /home/evan/electron/electron-boilerplate/node_modules/mocha/lib/mocha.js:219:27
    at Array.forEach (native)
    at Mocha.loadFiles (/home/evan/electron/electron-boilerplate/node_modules/mocha/lib/mocha.js:216:14)
    at Mocha.run (/home/evan/electron/electron-boilerplate/node_modules/mocha/lib/mocha.js:468:10)
    at Object.run (/home/evan/electron/electron-boilerplate/node_modules/electron-mocha/mocha.js:60:28)
    at EventEmitter.<anonymous> (/home/evan/electron/electron-boilerplate/node_modules/electron-mocha/index.js:45:11)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
```

This one I do not understand, I have changed no code. The line it is complaining about is `const app$1 = electron.remote.app;` transpiled from:
```
import { remote } from 'electron';
const app = remote.app;
```

the build script and application run fine with npm start, it only fails to build when I run `npm test` after the change to electron-mocha

**Comment by szwacz** [comment]
electron-mocha by default runs tests in browser process, and window object is reachable only in renderer process. This should fix the issue for you: https://github.com/szwacz/electron-boilerplate/commit/ef82d5d55064d0a089c5bdd9bdb50723afa240c9
