### ISSUE TITLE
Error when making a release

### ISSUE THREAD

**Issue by LeMoussel** [szwacz/electron-boilerplate#18]
On Windows 7, when I make for distribution installer with command: `npm run release`,  I got error.
`Failed at the @ release script 'gulp release --env=production`

Here the contain of `npm-debug.log` file
 
```
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Applications\\nodejs\\\\node.exe',
1 verbose cli   'D:\\Applications\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'release' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose run-script [ 'prerelease', 'release', 'postrelease' ]
5 info prerelease @
6 info release @
7 verbose unsafe-perm in lifecycle true
8 info @ Failed to exec release script
9 verbose stack Error: @ release: `gulp release --env=production`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (D:\Applications\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (D:\Applications\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1015:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
10 verbose pkgid @
11 verbose cwd C:\Users\lemoussel\SkyDrive\Electron\electron-boilerplate
12 error Windows_NT 6.1.7601
13 error argv "D:\\Applications\\nodejs\\\\node.exe" "D:\\Applications\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "release"
14 error node v0.12.7
15 error npm  v2.11.3
16 error code ELIFECYCLE
17 error @ release: `gulp release --env=production`
17 error Exit status 1
18 error Failed at the @ release script 'gulp release --env=production'.
18 error This is most likely a problem with the  package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     gulp release --env=production
18 error You can get their info via:
18 error     npm owner ls
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

**Comment by szwacz** [comment]
Have you installed NSIS as it's written readme?

**Comment by LeMoussel** [comment]
Oups, Désolé 
I am confused because I forgot paragraph "Special precautions for Windows"

It's OK
