### ISSUE TITLE
when npm install, node-gyp rebuild macos-aliase error 

### ISSUE THREAD

**Issue by zhangmingze** [szwacz/electron-boilerplate#197]
```shell
[macos-alias@0.2.9] scripts.install: "node-gyp rebuild" at C:\Users\mz\Desktop\KK6\node_modules\.npminstall\macos-alias\0.2.9\macos-alias
  volume.cc
..\src\volume.cc(9): fatal error C1189: #error :  This platform is not implemen
ted yet [C:\Users\mz\Desktop\KK6\node_modules\.npminstall\macos-alias\0.2.9\mac
os-alias\build\volume.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\mz\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mz\\AppData\\Roaming\\npm\\node_modules\\cnpm\\node_modules\\npminstall\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\mz\Desktop\KK6\node_modules\.npminstall\macos-alias\0.2.9\macos-alias
gyp ERR! node -v v6.3.1
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
Error: post install error, please remove node_modules before retry!
Run "C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp rebuild" error, exit code 1
Error: post install error, please remove node_modules before retry!
Run "C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp rebuild" error, exit code 1
    at ChildProcess.proc.on.code (C:\Users\mz\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\node_modules\runscript\index.js:67:21)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
```

win10
node -v 6.3.1
node-gyp -v 3.4.0

**Comment by black-snow** [comment]
This is rather an issue with `macos-alias` or with your setup. Why are you trying to use `macos-alias` on a win10 machine? How's that supposed to work?

**Comment by carvind** [comment]
`macos-alias` is only supported for `darwin` platform. [See Here](https://github.com/LinusU/node-alias/blob/master/package.json#L12)

**Comment by zhangmingze** [comment]
@black-snow @carvind thanks, it's solved
