### ISSUE TITLE
BadArgument on spawn

### ISSUE THREAD

**Issue by leshow** [szwacz/electron-boilerplate#208]
I have a project based off this boilerplate, I recently merged some updates that you've added. 

I ended up getting this error and I'm a bit stuck as to what the issue is. I haven't made any modifications to the build or bundle/start scripts.

```
Starting 'start'...
[11:04:40] 'start' error after 5.03ms
TypeError: Bad argument
at TypeError (native)
at ChildProcess.spawn (internal/child_process.js:274:26)
at Gulp.<anonymous> (c:\Users\test\electron-lobby\tasks\start.js:9:18)
at module.exports (c:\Users\test\electron-lobby\node_modules\orchestrator\lib\runTask.js:34:7)
at Gulp.Orchestrator._runTask (c:\Users\test\electron-lobby\node_modules\orchestrator\index.js:273:3)
....

```

kind of a shot in the dark, but any idea what this might be?

the line it's erroring at is childProcess.spawn(electron, ['./app']

**Comment by szwacz** [comment]
I would suspect the electron package name change from `electron-prebuilt` to `electron` to be the culprit. Are you sure you have `electron`package installed and not the old one?

**Comment by leshow** [comment]
that was it, thanks
