### ISSUE TITLE
Error: spawn EACCES

### ISSUE THREAD

**Issue by amelkikh** [szwacz/electron-boilerplate#217]
OS: Linux  3.19.0-32-generic #37~14.04.1-Ubuntu SMP Thu Oct 22 09:41:40 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux (Linux Mint Rose)

Log:

```
$ npm start

> @ start /media/developer/D8E27EADE27E8F8C/work/github/electron/electron-boilerplate
> gulp start

[20:14:25] Using gulpfile /media/developer/D8E27EADE27E8F8C/work/github/electron/electron-boilerplate/gulpfile.js
[20:14:25] Starting 'bundle'...
[20:14:25] Starting 'less'...
[20:14:25] Starting 'environment'...
[20:14:25] Finished 'environment' after 2.31 ms
[20:14:25] Starting 'watch'...
[20:14:25] Finished 'watch' after 9.64 ms
[20:14:25] Finished 'bundle' after 139 ms
[20:14:25] Finished 'less' after 162 ms
[20:14:25] Starting 'build'...
[20:14:25] Finished 'build' after 1.65 μs
[20:14:25] Starting 'start'...
[20:14:25] 'start' errored after 4.8 ms
[20:14:25] Error: spawn EACCES
    at exports._errnoException (util.js:1026:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at Object.exports.spawn (child_process.js:380:9)
    at Gulp.<anonymous> (/media/developer/D8E27EADE27E8F8C/work/github/electron/electron-boilerplate/tasks/start.js:8:18)
    at module.exports (/media/developer/D8E27EADE27E8F8C/work/github/electron/electron-boilerplate/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/media/developer/D8E27EADE27E8F8C/work/github/electron/electron-boilerplate/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/media/developer/D8E27EADE27E8F8C/work/github/electron/electron-boilerplate/node_modules/orchestrator/index.js:214:10)
    at /media/developer/D8E27EADE27E8F8C/work/github/electron/electron-boilerplate/node_modules/orchestrator/index.js:279:18
    at finish (/media/developer/D8E27EADE27E8F8C/work/github/electron/electron-boilerplate/node_modules/orchestrator/lib/runTask.js:21:8)
    at module.exports (/media/developer/D8E27EADE27E8F8C/work/github/electron/electron-boilerplate/node_modules/orchestrator/lib/runTask.js:60:3)
^C

```

**Comment by szwacz** [comment]
`EACCES` means most probably that current user has no rights to execute the electron file. Please do `console.log(electron)` in file `tasks/start.js` and ensure that you have rights to execute the path which appear in the logs.
