### ISSUE TITLE
Running after installation on Ubuntu 16.04 fails

### ISSUE THREAD

**Issue by jwir3** [szwacz/electron-boilerplate#221]
I've prepared my application, Arbitrator (source code available at http://github.com/jwir3/arbitrator/ ), and run the following command to prepare the release: `npm run-script release`. This (after some time) creates a dist/ directory, with a file called `Arbitrator-2.0.0.deb` inside of it, along with a `/linux/` subdirectory. Installing the .deb file allows me to run `Arbitrator` on the command line, but when I do so, it fails with:

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'googleapis'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/opt/Arbitrator/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at /opt/Arbitrator/resources/app.asar/background.js:8:14
    at Object.<anonymous> (/opt/Arbitrator/resources/app.asar/background.js:2062:2)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
```

Similarly, running `dist/linux/Arbitrator` also fails with the same error. I believe I might be doing something incorrect when packaging the application, since it seems to work just fine if I run `npm install && npm start` within the application directory (prior to packaging). Can you give me some advice on how to get it to work with the packaging utility?

**Comment by black-snow** [comment]
Dunno if it causes trouble but I guess you shouldn't have you app dependencies in the top-level `package.json`.

**Comment by jwir3** [comment]
Ok, I'll try that. Thanks @black-snow.
