### ISSUE TITLE
EACCES

### ISSUE THREAD

**Issue by Joe-the-mage** [szwacz/electron-boilerplate#223]
This is the error from yarn start (exactly the same for npm start). The address on the first line is from `console.log(electron)` as suggested in a previous issue. I have already used chown on all the usual suspects like /usr/lib. I'm running node 7.1.0, yarn 0.16.1, npm 4.0.2 on a MacOS Sierra 10.12.1 running on a macbook pro.

Thanks for any insight or workarounds!

```
> [20:40:20] Using gulpfile ~/Documents/Rebates_03/electron-boilerplate/gulpfile.js
> [20:40:20] Starting 'bundle'...
> [20:40:20] Starting 'less'...
> [20:40:20] Starting 'environment'...
> [20:40:20] Finished 'environment' after 1.85 ms
> [20:40:20] Starting 'watch'...
> [20:40:20] Finished 'watch' after 7.21 ms
> [20:40:20] Finished 'bundle' after 96 ms
> [20:40:20] Finished 'less' after 115 ms
> [20:40:20] Starting 'build'...
> [20:40:20] Finished 'build' after 29 μs
> [20:40:20] Starting 'start'...
> [20:40:20] 'start' errored after 3.35 ms
> [20:40:20] Error: spawn EACCES
>     at exports._errnoException (util.js:1022:11)
>     at ChildProcess.spawn (internal/child_process.js:313:11)
>     at Object.exports.spawn (child_process.js:385:9)
>     at Gulp.<anonymous> (/Users/joe/Documents/Rebates_03/electron-boilerplate/tasks/start.js:10:18)
>     at module.exports (/Users/joe/Documents/Rebates_03/electron-boilerplate/node_modules/orchestrator/lib/runTask.js:34:7)
>     at Gulp.Orchestrator._runTask (/Users/joe/Documents/Rebates_03/electron-boilerplate/node_modules/orchestrator/index.js:273:3)
>     at Gulp.Orchestrator._runStep (/Users/joe/Documents/Rebates_03/electron-boilerplate/node_modules/orchestrator/index.js:214:10)
>     at /Users/joe/Documents/Rebates_03/electron-boilerplate/node_modules/orchestrator/index.js:279:18
>     at finish (/Users/joe/Documents/Rebates_03/electron-boilerplate/node_modules/orchestrator/lib/runTask.js:21:8)
>     at module.exports (/Users/joe/Documents/Rebates_03/electron-boilerplate/node_modules/orchestrator/lib/runTask.js:60:3)
> 
```

**Comment by black-snow** [comment]
See if http://stackoverflow.com/questions/33741367/gulp-watch-failing-with-spawn-eacces-error helps.
Have you checked permissions of your app files? Can't reproduce on Sierra.

**Comment by szwacz** [comment]
If I'm reading this correctly the script is failing on line:
```js
childProcess.spawn(electron, ['./app'], {
    stdio: 'inherit'
})
```
So looks like just doesn't have the right to execute electron runtime.

Are you sure that your user has execution rights for path returned by `console.log(electron)`?
