### ISSUE TITLE
install error related to node-gyp

### ISSUE THREAD

**Issue by dland512** [szwacz/electron-boilerplate#278]
Just trying a basic installation on macOS Sierra (10.12.5) and I'm getting this error:
```
$ npm i

> fcopy-pre-bundled@0.1.2 install /Users/dave/Desktop/electron-boilerplate/node_modules/fcopy-pre-bundled
> node-gyp rebuild

gyp: binding.gyp not found (cwd: /Users/dave/Desktop/electron-boilerplate/node_modules/fcopy-pre-bundled) while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/dave/Desktop/electron-boilerplate/node_modules/fcopy-pre-bundled
gyp ERR! node -v v6.11.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
electron-boilerplate@0.0.0 /Users/dave/Desktop/electron-boilerplate
└── (empty)
```

Any ideas?

**Comment by szwacz** [comment]
Looks like it was `electron-builder` problem. Bumping that dependency to latest version helped on my machine. Please try git pull, npm install again.

**Comment by dland512** [comment]
Looks like that fixed it, thanks!
