### ISSUE TITLE
npm test , npm run release error    application launch     1) "before each" hook: beforeEach for "shows hello world text on screen after launch"     0 passing (2s)   1 failing    1) application launch        "before each" hook: beforeEach for "shows hello world text on screen after launch":      Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\electrons\szwacz.electron-boilerplate\temp\e2e.js)       at listOnTimeout (internal/timers.js:549:17)       at processTimers (internal/timers.js:492:7)

### ISSUE THREAD

**Issue by leodesigndev** [szwacz/electron-boilerplate#315]
$ npm run test or npm run release give the following error

**Comment by bwiessneth** [comment]
Quick workaround: Add a timeout option to the e2e script in **package.json**:

    "e2e": "mocha temp/e2e.js --require source-map-support/register --timeout 10000",

**Comment by szwacz** [comment]
Have risen default timeout to 10s by default.
