### ISSUE TITLE
Npm test fails

### ISSUE THREAD

**Issue by cool-html5** [szwacz/electron-boilerplate#320]
I just cloned this repo and run npm i and npm test. I have not made any changes. The test fails with the following error:

> mocha temp/e2e.js --require source-map-support/register

  application launch
    √ shows hello world text on screen after launch
    1) "after each" hook: afterEach for "shows hello world text on screen after launch"

  1 passing (4s)
  1 failing

  1) application launch
       "after each" hook: afterEach for "shows hello world text on screen after launch":
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\Users\jarkkop\source\repos\electron-boilerplate\temp\e2e.js)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

**Comment by PxlCode** [comment]
### Same here!

Did a fresh clone. 

`npm install` => `npm start` => WORKS!
 But `npm test` fails with the same error. The unit-tests are working.

**Console Ouput**
```console
> mocha temp/e2e.js --require source-map-support/register

  application launch
    √ shows hello world text on screen after launch
    1) "after each" hook: afterEach for "shows hello world text on screen after launch"

  1 passing (4s)
  1 failing

  1) application launch
       "after each" hook: afterEach for "shows hello world text on screen after launch":
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\Users\patri\Documents\projekte\electron-boilerplate\temp\e2e.js)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)
```

As we see the error got thrown in the `afterEach` in `./app/e2e/utils.js` after the second e2e test.
The console output can be confusing when the error gets thrown in a hook.

The test itself is alright.
- I tried adding a `done()` to the test and get a expected overspecifing error when using `done()` with `return <Promise>`.
- looked at how the *.config.js are build. Dont know much about it. 
- I `console.log(app);` in `afterEach` and it's defined and `running: true`.
- **Adding a timeout to the `afterEach` Root-Hook of `10000` resulted in another error => `TypeError: Cannot read property 'client' of undefined`, because as I removde the timeout from the `beforeEach` I ran into the same error but from the `beforeEach` and got curious**

```
 "before each" hook: beforeEach for "shows hello world text on screen after launch":
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\Users\patri\Documents\projekte\electron-boilerplate\temp\e2e.js)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)
```

As I struggle myself to get [electron-mocha](https://github.com/jprichardson/electron-mocha) running and just running into different problems across the way, I wanted to join the conversation.

**Comment by szwacz** [comment]
Spectron defined default timeout for a test od 2000ms, the test setup takes more than that hence the error. I've risen the timeout to 10000ms in the code long time ago: https://github.com/szwacz/electron-boilerplate/blob/master/e2e/utils.js#L5
That means Spectron in your case ignored this timeout change. 

The code works fine on my MacOS machine, can you test in yours moving the `this.timeout(10000)` into test itself, as it's done in Spectron readme: https://github.com/electron-userland/spectron/blob/master/README.md 
Maybe this issue is only reproducable on Windows platform, to which I don't have easy access right now (need to install a VM).

**Comment by cool-html5** [comment]
The e2e/utils.js already has a timeout of 10 seconds. This is not the solution to the problem. Yes this might only be a windows platform issue.

**Comment by szwacz** [comment]
Ah, right, I was combating the timeouts in `beforeEach` so much in the past, that didn't notice the `afterEach` word in your logs. Man, Spectron (webdriver?) is a flaky thing. I suspect this is a problem with Spectron itself, since `afterEach` function is just closing the app window, don't see what might take long there.

Unfortunately Cypress doesn't have Electron support on their roadmap so far.

**Comment by szwacz** [comment]
FYI, Spectron just announced sun-setting the project: https://github.com/electron-userland/spectron/issues/1045
Interesting how situation is going to unwind.
