### ISSUE TITLE
Transpiling not compatible with the preload option on BrowserWindow

### ISSUE THREAD

**Issue by antoinepairet** [szwacz/electron-boilerplate#37]
The `preload` option is not working due to the build script:

````js
mainWindow = new BrowserWindow({
    // ... other options
    preload: path.join(__dirname, '/myPreloadedScript.js')
````

The built version (found under `/build` folder) is wrapped inside `define(['exports'], function (exports) {` leading to the following error:

````
ReferenceError: define is not defined
    at Object.<anonymous> (C:\electronApp\build\myPreloadedScript.js:1:63)
    at Module._compile (module.js:430:26)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\electronApp\node_modules\electron-prebuilt\dist\resources\atom.asar\renderer\lib\init.js:94:7)
    at Object.<anonymous> (C:\electronApp\electronApp\node_modules\electron-prebuilt\dist\resources\atom.asar\renderer\lib\init.js:106:4)
    at Module._compile (module.js:430:26)(anonymous function) @ C:\electronApp\electronApp\node_modules\electron-prebuilt\dist\resources\atom.asar\renderer\lib\init.js:101
```` 

Preloaded js file should not be transpiled.
One PR will follow

**Comment by szwacz** [comment]
Now the boilerplate uses bundler with single file as a entry, so stuff isn't transpiled by `*.js` glob any longer.
