### ISSUE TITLE
Gulp Watch Errors Preventing App from Opening in Windows

### ISSUE THREAD

**Issue by tysenmoore-xse** [szwacz/electron-boilerplate#46]
I have a situation where I have added a directory (./app/sdk/...).  Under this `sdk` directory I have Linux shared objects and  Windows DLL's.  I also have added `"./sdk/**"` to the `./tasks/build.js` `paths.copyFromAppDir`.  When I run under Linux I have no problems: files are copied and the app opens fine.  However, if I change to Windows I get gulp errors and files do not copy:

    [13:44:28] 'watch' errored after 649 ms
    [13:44:28] Error: EPERM: operation not permitted, scandir 'Z:\work\tmp\hmi\app\sdk\linux\libanlzr.so.orig'
        at Error (native)
        at Object.fs.readdirSync (fs.js:813:18)
        at Glob._readdir (Z:\work\tmp\hmi\node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-watcher\node_modules\gaze\node_modules\globule\node_modules\glob\glob.js:577:20)
        at Glob._process (Z:\work\tmp\hmi\node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-watcher\node_modules\gaze\node_modules\globule\node_modules\glob\glob.js:379:15)
        at Glob.<anonymous> (Z:\work\tmp\hmi\node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-watcher\node_modules\gaze\node_modules\globule\node_modules\glob\glob.js:403:14)
        at Array.forEach (native)
        at Glob.<anonymous> (Z:\work\tmp\hmi\node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-watcher\node_modules\gaze\node_modules\globule\node_modules\glob\glob.js:402:9)
        at Glob._readdir (Z:\work\tmp\hmi\node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-watcher\node_modules\gaze\node_modules\globule\node_modules\glob\glob.js:554:32)
        at Glob._process (Z:\work\tmp\hmi\node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-watcher\node_modules\gaze\node_modules\globule\node_modules\glob\glob.js:379:15)
        at Glob.<anonymous> (Z:\work\tmp\hmi\node_modules\gulp\node_modules\vinyl-fs\node_modules\glob-watcher\node_modules\gaze\node_modules\globule\node_modules\glob\glob.js:403:14)

It seems the copy process fails to copy most of the files even though I don't see any other errors reported.

Also, just prior to the error being displayed I get a dialog box:

    Error Opening App
    "The app provided is not a valid...."

    Error: Cannot find module: './vendor/electron_boilerplate/env_config'

If I remove the `sdk` directory all together, the problem goes away.  Also, if I only remove the `sdk/linux` directory so no Linux shared libraries are found, the problem goes away.

Is there something else I need to configure so these offending files are not watched or copied?  How can I get Windows to ignore the Linux directory?  (or any directory for that matter).  Thanks for the time and any suggestions.

**Comment by szwacz** [comment]
The error is: `Object.fs.readdirSync` failed with `EPERM`, so this linux folder doesn't have proper access permissions on windows. Do you share the same project folder on linux and windows machines?

**Comment by tysenmoore-xse** [comment]
Thanks so much.  There was a difference in the permissions.  The strange thing was deleting and recreating the directory did not help.  I have modified my setup to work around the problem by using the npm install phase to copy only the necessary files.  Thanks so much for the time and help.
