### ISSUE TITLE
[Error: Cannot find module 'appdmg'] code: 'MODULE_NOT_FOUND' }

### ISSUE THREAD

**Issue by zverbatim** [szwacz/electron-boilerplate#55]
When running `npm run release` (os x 10.10.5) i get `[Error: Cannot find module 'appdmg'] code: 'MODULE_NOT_FOUND' }`

The built app runs fine though. 
Curious what this errors means.

Versions:
npm: 2.10.1
electron: 0.33.0

**Comment by jonatasfreitasv** [comment]
You run npm install in project root folder ?

**Comment by jonatasfreitasv** [comment]
Or re-run `npm install appdmg` in root folder...

**Comment by paperscissors** [comment]
I get this error as well, on 10.10.5. I don't actually get a successful build in releases, however. The directory is empty.

Tried re-running npm install and npm install appdmg and I get:
```
electron-boilerplate user$ npm install
npm WARN package.json @ No repository field.
npm WARN package.json @ No license field.
 
> fs-xattr@0.1.11 install ../electron-boilerplate/node_modules/appdmg/node_modules/fs-xattr
> node-gyp rebuild

  CXX(target) Release/obj.target/xattr/src/error.o
  CXX(target) Release/obj.target/xattr/src/xattr.o
  SOLINK_MODULE(target) Release/xattr.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/xattr.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd ../electron-boilerplate/node_modules/appdmg/node_modules/fs-xattr
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 

> macos-alias@0.2.9 install ../electron-boilerplate/node_modules/appdmg/node_modules/ds-store/node_modules/macos-alias
> node-gyp rebuild

  CXX(target) Release/obj.target/volume/src/volume.o
  SOLINK_MODULE(target) Release/volume.node
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/volume.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd ../electron-boilerplate/node_modules/appdmg/node_modules/ds-store/node_modules/macos-alias
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm WARN optional dep failed, continuing appdmg@0.3.5

> @ postinstall ../electron-boilerplate
> node ./tasks/app_npm_install

npm WARN package.json electron-boilerplate@0.1.0 No repository field.
npm WARN package.json electron-boilerplate@0.1.0 No README data
npm WARN package.json electron-boilerplate@0.1.0 No license field.
```
Same thing if I try npm install appdmg.

npm version
{ npm: '2.14.1',
  http_parser: '2.3',
  modules: '14',
  node: '0.12.7',
  openssl: '1.0.1p',
  uv: '1.6.1',
  v8: '3.28.71.19',
  zlib: '1.2.8' }

**Comment by szwacz** [comment]
So this looks like purely problem with appdmg module, then you can report it to the author of that library.

**Comment by paperscissors** [comment]
Will do, thanks!
