### ISSUE TITLE
Windows 10: Error when trying to run blank boilerplate

### ISSUE THREAD

**Issue by intellent** [szwacz/electron-boilerplate#57]
I installed Node 4.2.1 and NSIS on Windows 10.

After `npm install` went through without errors, `npm start` produces the following output:

    Z:\>npm start

    > @ start Z:\
    > node ./tasks/start

    [13:10:54] Using gulpfile Z:\gulpfile.js
    module.js:339
        throw err;
        ^

    Error: Cannot find module 'Z:node_modules\gulp\index.js'
        at Function.Module._resolveFilename (module.js:337:15)
        at Function.Module._load (module.js:287:25)
        at Module.require (module.js:366:17)
        at require (module.js:385:17)
        at Liftoff.handleArguments (Z:\node_modules\gulp\bin\gulp.js:119:18)
        at Liftoff.<anonymous> (Z:\node_modules\gulp\node_modules\liftoff\index.js:192:16)
        at module.exports (Z:\node_modules\gulp\node_modules\liftoff\node_modules\flagged-respawn\index.js:17:3)
        at Liftoff.<anonymous> (Z:\node_modules\gulp\node_modules\liftoff\index.js:185:9)
        at Z:\node_modules\gulp\node_modules\liftoff\index.js:159:9
        at Z:\node_modules\gulp\node_modules\v8flags\index.js:99:14
    [13:10:58] Using gulpfile Z:\gulpfile.js
    module.js:339
        throw err;
        ^

    Error: Cannot find module 'Z:node_modules\gulp\index.js'
        at Function.Module._resolveFilename (module.js:337:15)
        at Function.Module._load (module.js:287:25)
        at Module.require (module.js:366:17)
        at require (module.js:385:17)
        at Liftoff.handleArguments (Z:\node_modules\gulp\bin\gulp.js:119:18)
        at Liftoff.<anonymous> (Z:\node_modules\gulp\node_modules\liftoff\index.js:192:16)
        at module.exports (Z:\node_modules\gulp\node_modules\liftoff\node_modules\flagged-respawn\index.js:17:3)
        at Liftoff.<anonymous> (Z:\node_modules\gulp\node_modules\liftoff\index.js:185:9)
        at Z:\node_modules\gulp\node_modules\liftoff\index.js:159:9
        at Z:\node_modules\gulp\node_modules\v8flags\index.js:99:14

**Comment by intellent** [comment]
Ok, seems to be a Gulp problem related to Windows. If I manually set the path in `node_modules\gulp\bin\gulp.js:119`, it works fine.

Will check, if there’s a corresponding issue at the Gulp repo. Can be closed, I guess.
