### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by leslyarun** [szwacz/electron-boilerplate#65]
Im getting the below error while running npm start:

````
C:\Users\arun\Documents\GitHub\electron-boilerplate>npm start

> @ start C:\Users\arun\Documents\GitHub\electron-boilerplate
> node ./tasks/start

fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'C:\Users\arun\Documents\GitHub\electron-boilerplate\node_modules\electron-prebuilt\path.txt'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.<anonymous> (C:\Users\arun\Documents\GitHub\electron-boilerplate\node_modules\electron-prebuilt\index.js:4:21)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\arun\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.1.1
npm ERR! npm  v2.11.0
npm ERR! code ELIFECYCLE
npm ERR! @ start: `node ./tasks/start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script 'node ./tasks/start'.
npm ERR! This is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./tasks/start
npm ERR! You can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\arun\Documents\GitHub\electron-boilerplate\npm-debug.log
````

**Comment by leslyarun** [comment]
tried that in bash, and working
