### ISSUE TITLE
`npm run release` failed on windows

### ISSUE THREAD

**Issue by liudonghua123** [szwacz/electron-boilerplate#8]
When I run `npm run release` on my Windows, I got the following error message.
```
E:\code\nodejs\electron-boilerplate>npm run release

> @ release E:\code\nodejs\electron-boilerplate
> gulp release --env=production

[10:49:29] Using gulpfile E:\code\nodejs\electron-boilerplate\gulpfile.js
[10:49:29] Starting 'clean'...
[10:49:30] Finished 'clean' after 141 ms
[10:49:30] Starting 'transpile'...
[10:49:30] Starting 'less'...
[10:49:30] Starting 'copy'...
[10:49:30] Starting 'finalize'...
[10:49:30] Finished 'finalize' after 23 ms
[10:49:30] Finished 'less' after 186 ms
[10:49:30] Finished 'transpile' after 299 ms
[10:49:31] Finished 'copy' after 1.24 s
[10:49:31] Starting 'build'...
[10:49:31] Finished 'build' after 14 µs
[10:49:31] Starting 'release'...
[10:49:37] Building installer with NSIS...
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn makensis ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "release"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE
npm ERR! @ release: `gulp release --env=production`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ release script 'gulp release --env=production'.
npm ERR! This is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp release --env=production
npm ERR! You can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\code\nodejs\electron-boilerplate\npm-debug.log

E:\code\nodejs\electron-boilerplate>
```

The content of `E:\code\nodejs\electron-boilerplate\npm-debug.log` is belows
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'release' ]
2 info using npm@2.10.1
3 info using node@v0.12.4
4 verbose run-script [ 'prerelease', 'release', 'postrelease' ]
5 info prerelease @
6 info release @
7 verbose unsafe-perm in lifecycle true
8 info @ Failed to exec release script
9 verbose stack Error: @ release: `gulp release --env=production`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1015:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
10 verbose pkgid @
11 verbose cwd E:\code\nodejs\electron-boilerplate
12 error Windows_NT 6.3.9600
13 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "release"
14 error node v0.12.4
15 error npm  v2.10.1
16 error code ELIFECYCLE
17 error @ release: `gulp release --env=production`
17 error Exit status 1
18 error Failed at the @ release script 'gulp release --env=production'.
18 error This is most likely a problem with the  package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     gulp release --env=production
18 error You can get their info via:
18 error     npm owner ls
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

```

My OS is Win8.1 x64, and node/npm version is
```
E:\code\nodejs\electron-boilerplate>node -v
v0.12.4

E:\code\nodejs\electron-boilerplate>npm -v
2.10.1

E:\code\nodejs\electron-boilerplate>
```

**Comment by carlosperate** [comment]
Have you got NSIS installed?

**Comment by liudonghua123** [comment]
No, I noticed that, now it works after I installed NSIS. I should read the doc more carefully. Thanks!
